In [1]:
import torch
import math
import torch.nn as nn
import torchvision.models
from torch.nn import functional as F

In [2]:
target_classes = torch.randn(2, 25)
target_classes.shape

torch.Size([2, 25])

In [3]:
new_target_classes = target_classes.reshape(-1)
new_target_classes.shape

torch.Size([50])

In [4]:
cls_idx_output = torch.randn(2, 25, 21)
cls_idx_output.shape

torch.Size([2, 25, 21])

In [5]:
new_cls_idx_output = cls_idx_output.reshape(-1, 21)
new_cls_idx_output.shape

torch.Size([50, 21])

In [6]:
cls_weights = torch.ones(21)
cls_weights

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.])

In [7]:
cls_weights[0] = 0.1

In [8]:
cls_weights

tensor([0.1000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000])

In [9]:
cls_output_example = torch.randn(2, 25, 21)
cls_output_example.shape

torch.Size([2, 25, 21])

In [10]:
cls_output_example

tensor([[[-1.2992,  0.5309, -0.1300,  ...,  0.2667, -0.7084, -0.6372],
         [-0.7756, -0.2657, -1.6369,  ...,  0.1144,  0.2791,  1.3968],
         [ 0.6413, -0.2504, -0.2796,  ...,  1.0618,  1.3654, -0.7977],
         ...,
         [-0.5615, -0.3113,  0.7321,  ..., -0.1316,  0.7646, -0.3861],
         [ 2.1539,  0.3353, -0.2219,  ...,  0.3284,  1.1422, -1.4208],
         [-0.6377, -0.6676,  0.4437,  ..., -0.1872,  0.3781,  1.4120]],

        [[ 0.1006,  1.1884,  0.3835,  ...,  0.8653,  0.5260, -0.6480],
         [-1.1924, -2.0702,  0.5452,  ...,  0.5038, -1.1414, -0.0611],
         [ 1.3851, -1.3050,  0.3755,  ..., -0.0566,  1.1919, -1.9499],
         ...,
         [ 1.7791, -1.3946, -1.1947,  ...,  0.9107, -0.0454,  0.6755],
         [ 0.0093,  1.3286, -0.7122,  ..., -0.3664, -0.0806,  0.5163],
         [ 0.7674, -0.6476,  0.1453,  ..., -0.1094,  1.7191,  0.7641]]])

In [11]:
prob = torch.nn.functional.softmax(cls_output_example, -1)
prob.shape

torch.Size([2, 25, 21])

In [12]:
prob

tensor([[[0.0061, 0.0381, 0.0197,  ..., 0.0293, 0.0110, 0.0119],
         [0.0175, 0.0291, 0.0074,  ..., 0.0426, 0.0502, 0.1535],
         [0.0555, 0.0228, 0.0221,  ..., 0.0846, 0.1146, 0.0132],
         ...,
         [0.0184, 0.0236, 0.0670,  ..., 0.0283, 0.0692, 0.0219],
         [0.0945, 0.0153, 0.0088,  ..., 0.0152, 0.0344, 0.0026],
         [0.0198, 0.0192, 0.0584,  ..., 0.0311, 0.0547, 0.1537]],

        [[0.0235, 0.0699, 0.0312,  ..., 0.0506, 0.0360, 0.0111],
         [0.0180, 0.0075, 0.1023,  ..., 0.0982, 0.0190, 0.0558],
         [0.1337, 0.0091, 0.0487,  ..., 0.0316, 0.1102, 0.0048],
         ...,
         [0.1745, 0.0073, 0.0089,  ..., 0.0732, 0.0281, 0.0579],
         [0.0372, 0.1393, 0.0181,  ..., 0.0256, 0.0340, 0.0618],
         [0.0613, 0.0149, 0.0329,  ..., 0.0255, 0.1587, 0.0611]]])

In [13]:
cls_output = torch.randn(2, 25, 21)
bbox_output = torch.randn(2, 25, 4)

In [14]:
print(cls_output.shape)
print(bbox_output.shape)

torch.Size([2, 25, 21])
torch.Size([2, 25, 4])


In [15]:
prob = torch.nn.functional.softmax(cls_output, -1)
prob.shape

torch.Size([2, 25, 21])

In [16]:
scores, labels = prob[..., :-1].max(-1)

In [17]:
print(scores.shape)
print(labels.shape)

torch.Size([2, 25])
torch.Size([2, 25])


In [18]:
boxes = bbox_output

In [19]:
scores_idx = scores[0]
scores_idx.shape

torch.Size([25])

In [20]:
labels_idx = labels[0]
labels_idx.shape

torch.Size([25])

In [21]:
boxes_idx = boxes[0]
labels_idx.shape

torch.Size([25])

In [22]:
keep_idxs = scores_idx >= 0.20

In [23]:
print(keep_idxs)
print(keep_idxs.shape)

tensor([False, False, False,  True,  True,  True, False, False, False, False,
        False,  True,  True, False, False,  True,  True,  True, False,  True,
        False, False, False, False,  True])
torch.Size([25])


In [24]:
scores_idx = scores_idx[keep_idxs]
scores_idx.shape

torch.Size([10])

In [25]:
print(scores_idx)
print(scores_idx.shape)

tensor([0.2228, 0.2039, 0.2219, 0.2824, 0.2189, 0.4017, 0.2329, 0.3325, 0.3475,
        0.3076])
torch.Size([10])


In [26]:
boxes_idx = boxes_idx[keep_idxs]
boxes_idx.shape

torch.Size([10, 4])

In [27]:
print(boxes_idx)
print(boxes_idx.shape)

tensor([[-0.3711, -0.4683, -1.0522, -1.6326],
        [ 0.4452,  2.1483, -0.4623, -0.7760],
        [ 0.3677, -0.2142, -0.4647, -0.5772],
        [-0.2771, -1.1762, -0.3785,  1.1011],
        [-0.8572,  0.4286, -1.1629,  0.2784],
        [ 0.4326,  0.8263, -0.1826, -0.5358],
        [-0.1839,  0.2451,  0.0611, -1.0570],
        [ 0.6581, -0.3389, -0.5418,  0.1617],
        [ 0.0486, -0.8081, -0.3484, -0.3294],
        [ 0.8520,  0.7651,  0.2566,  0.2078]])
torch.Size([10, 4])


In [28]:
labels_idx = labels_idx[keep_idxs]
labels_idx.shape

torch.Size([10])

In [29]:
print(labels_idx)
print(labels_idx.shape)

tensor([ 9, 15, 17,  1, 15, 15,  6, 15, 16,  3])
torch.Size([10])


In [30]:
keep_idxs = torchvision.ops.batched_nms(boxes_idx, scores_idx, labels_idx, 0.7)
keep_idxs.shape

torch.Size([10])

In [31]:
scores_idx = scores_idx[keep_idxs]

In [32]:
print(scores_idx)
print(scores_idx.shape)

tensor([0.4017, 0.3475, 0.3325, 0.3076, 0.2824, 0.2329, 0.2228, 0.2219, 0.2189,
        0.2039])
torch.Size([10])


In [33]:
boxes_idx = boxes_idx[keep_idxs]

In [34]:
print(boxes_idx)
print(boxes_idx.shape)

tensor([[ 0.4326,  0.8263, -0.1826, -0.5358],
        [ 0.0486, -0.8081, -0.3484, -0.3294],
        [ 0.6581, -0.3389, -0.5418,  0.1617],
        [ 0.8520,  0.7651,  0.2566,  0.2078],
        [-0.2771, -1.1762, -0.3785,  1.1011],
        [-0.1839,  0.2451,  0.0611, -1.0570],
        [-0.3711, -0.4683, -1.0522, -1.6326],
        [ 0.3677, -0.2142, -0.4647, -0.5772],
        [-0.8572,  0.4286, -1.1629,  0.2784],
        [ 0.4452,  2.1483, -0.4623, -0.7760]])
torch.Size([10, 4])


In [35]:
labels_idx = labels_idx[keep_idxs]

In [36]:
print(labels_idx)
print(labels_idx.shape)

tensor([15, 16, 15,  3,  1,  6,  9, 17, 15, 15])
torch.Size([10])
