In [3]:
import torch
import math
import torch.nn as nn
import torchvision.models
from torch.nn import functional as F

In [19]:
target_classes = torch.randn(2, 25)
target_classes.shape

torch.Size([2, 25])

In [20]:
new_target_classes = target_classes.reshape(-1)
new_target_classes.shape

torch.Size([50])

In [28]:
cls_idx_output = torch.randn(2, 25, 21)
cls_idx_output.shape

torch.Size([2, 25, 21])

In [29]:
new_cls_idx_output = cls_idx_output.reshape(-1, 21)
new_cls_idx_output.shape

torch.Size([50, 21])

In [34]:
cls_weights = torch.ones(21)
cls_weights

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.])

In [35]:
cls_weights[0] = 0.1

In [39]:
cls_weights

tensor([0.1000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000])

In [44]:
cls_output_example = torch.randn(2, 25, 21)
cls_output_example.shape

torch.Size([2, 25, 21])

In [45]:
cls_output_example

tensor([[[-0.4485,  0.1101, -0.8145,  ...,  0.5465,  0.0609,  1.4846],
         [ 0.2268,  0.1925, -0.8024,  ..., -2.1785,  1.3658, -0.1389],
         [-0.4121, -0.6782, -0.1494,  ...,  1.2998,  0.5364, -0.5084],
         ...,
         [ 0.4792,  0.5789,  0.1912,  ...,  0.6979,  0.2246, -1.1711],
         [-1.1580,  0.1313, -0.0362,  ..., -0.5719,  1.2292, -0.3442],
         [ 1.6303, -0.3293,  0.7745,  ...,  1.1632,  0.7821, -0.7629]],

        [[-1.1581,  1.4844,  1.5880,  ..., -0.0118, -0.4796, -0.8489],
         [ 1.4133,  0.9977, -0.3982,  ...,  1.3520, -0.6553, -0.4587],
         [ 0.4665, -0.6109, -1.7494,  ...,  0.0859, -2.0414,  1.5802],
         ...,
         [ 0.6856,  0.1255, -1.5579,  ..., -0.1005,  0.7026, -0.3090],
         [ 1.2609,  0.0629, -3.0110,  ...,  1.0811,  0.3197,  0.6429],
         [-0.9042,  0.0861,  0.4567,  ...,  0.1014, -0.7584, -0.1538]]])

In [46]:
prob = torch.nn.functional.softmax(cls_output_example, -1)
prob.shape

torch.Size([2, 25, 21])

In [47]:
prob

tensor([[[0.0155, 0.0271, 0.0108,  ..., 0.0420, 0.0258, 0.1073],
         [0.0552, 0.0534, 0.0197,  ..., 0.0050, 0.1725, 0.0383],
         [0.0253, 0.0194, 0.0328,  ..., 0.1399, 0.0652, 0.0229],
         ...,
         [0.0508, 0.0561, 0.0381,  ..., 0.0632, 0.0394, 0.0098],
         [0.0117, 0.0424, 0.0358,  ..., 0.0210, 0.1270, 0.0263],
         [0.1237, 0.0174, 0.0526,  ..., 0.0776, 0.0530, 0.0113]],

        [[0.0093, 0.1305, 0.1448,  ..., 0.0292, 0.0183, 0.0127],
         [0.1845, 0.1217, 0.0301,  ..., 0.1735, 0.0233, 0.0284],
         [0.0699, 0.0238, 0.0076,  ..., 0.0478, 0.0057, 0.2128],
         ...,
         [0.0583, 0.0333, 0.0062,  ..., 0.0266, 0.0593, 0.0216],
         [0.1167, 0.0352, 0.0016,  ..., 0.0975, 0.0455, 0.0629],
         [0.0130, 0.0350, 0.0507,  ..., 0.0355, 0.0150, 0.0275]]])